# Generated by Django 4.1.3 on 2022-11-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ImageModel",
        ),
        migrations.RenameModel(
            old_name="Item",
            new_name="ItemModel",
        ),
    ]
